version: "3.8"

volumes:
  base_volume: { }

networks:
  net:
    external: true

services:

  base:
    container_name: base
    image: postgres:11.10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: story
    networks:
      - net
    volumes:
      - base_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432