micronaut:
  application:
    name: stories

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    url: "${BASE_URL}"
    driverClassName: org.postgresql.Driver
    username: postgres
    password: "${BASE_PASSWORD}"
    dialect: POSTGRES

jpa:
  default:
    entity-scan:
      packages: 'tech.threecrabs'
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: none
        show_sql: true

flyway:
  datasources:
    default:
      enabled: true